<?php

use Illuminate\Database\Seeder;

class LogradouroTipoTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Aeroporto'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Alameda'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Área'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Avenida'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Balneário'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Bosque'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Calçada'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Campo'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Chácara'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Colônia'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Condomínio'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Conjunto'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Distrito'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Esplanada'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Estação'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Estrada'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Favela'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Feira'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Ferrovia'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Jardim'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Ladeira'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Lago'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Lagoa'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Largo'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Loteamento'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Morro'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Núcleo'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Parque'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Passarela'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Pátio'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Praça'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Quadra'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Recanto'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Residencial'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Rodovia'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Rua'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Serra'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Setor'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Sítio'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Travessa'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Trecho'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Trevo'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Vale'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Vereda'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Via'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Viaduto'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Viela'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Vila'
        ]);
        DB::table('tb_logradouro_tipo')->insert([
            'tp_log_descricao'=>'Outro'
        ]);
    }
}
